### ISSUE TITLE
How is it crop circle?

### ISSUE THREAD

**Issue by zanjs** [h2non/imaginary#147] opened 2017-08-16 03:11 UTC
Is it possible to take a square or rectangle image and crop it to a circle with this library?

**Comment by Dynom** [comment] 2017-08-16 06:06
This seems a duplicate of the same issue reported by you here: https://github.com/h2non/bimg/issues/176

I'm not sure what yo mean by "circle crop". I'm assuming you're referring to masking? Libvips has support for it, but I'm not aware of it being supported by Imaginary (or bimg)

**Comment by h2non** [comment] 2017-08-16 09:23
@Dynom is right. Closing because of duplication.

**Closed by h2non** 2017-08-16 09:23 UTC
