### ISSUE TITLE
Docker image: Watermark operation - Error while processing the image: VipsOperation: class "text" not found

### ISSUE THREAD

**Issue by sonu27** [h2non/imaginary#31] opened 2015-10-06 09:51 UTC
When running the docker image on OS X (Yosemite), and using the watermark operation, I get this error:
```{
message: "Error while processing the image: VipsOperation: class "text" not found",
code: 1
}```

**Comment by h2non** [comment] 2015-10-06 10:18
Which version of libvips are you using? Are you passing the proper `text` query param?

**Comment by sonu27** [comment] 2015-10-06 10:19
Sorry forgot to mention this happens on the /form testing page.
How do I check the version?
It's the one that comes with the latest docker build.

**Comment by h2non** [comment] 2015-10-06 10:28
Be sure you are running the latest `imaginary` version, pulling from `master`. 
Then, if you make a GET request to `/` you should see JSON returning the current versions.

**Comment by sonu27** [comment] 2015-10-06 10:29
imaginary server 0.1.9

**Comment by h2non** [comment] 2015-10-06 10:30
Try pulling the latest: [0.1.15](https://hub.docker.com/r/h2non/imaginary/tags).

**Comment by sonu27** [comment] 2015-10-06 10:37
Ok trying that now.
But the latest tag isn't working correctly.
You may need to update it each time, it's pointing to an old version: https://hub.docker.com/r/h2non/imaginary/tags/

**Comment by sonu27** [comment] 2015-10-06 10:41
Same thing happens:
```
{
imaginary: "0.1.15",
bimg: "0.1.21",
libvips: "8.0.2"
}
```

**Comment by h2non** [comment] 2015-10-06 11:58
I see now. I'll fix the docker tag.

The issue is probably due to the `libvips` version, it works fine with `7.40`. watermark feature is not fully supported yet.

**Comment by h2non** [comment] 2015-10-06 12:53
Docker tag was fixed. Now you can use latest. I'm gonna reproduce the issue using libvips `8.x`, and based on that, perhaps I'll release a new release (and Docker tag too) which uses libvips `7.42.3`, as intermediate solution until the support with `8.x` is done.

**Comment by sonu27** [comment] 2015-10-06 13:23
Wow. That was amazingly fast.

**Comment by sonu27** [comment] 2015-10-06 13:34
Deleted all my images, and refetched the latest image.
It still uses ```libvips: "8.0.2"```
Also, the latest tag doesn't work correctly, as the image didn't auto update.
I had to delete it and refetch latest. :(

**Comment by h2non** [comment] 2015-10-06 13:36
Too fast, dude. I'm still working on it. I'll let you know.

**Comment by h2non** [comment] 2015-10-06 14:01
Breaking news: I was wrong: the issue we're covering here is not related to compatibility inconsistencies in different `libvips` versions, which is actually in some way positive. 

I guess it's due to an unsatisfied dependency when compiling, especially in raw Linux distributions without graphical environment. To be more concrete, I'm talking about [pango](http://www.pango.org), which is internally used by `libvips` to render text-based stuff.

I'm digging into the proper solution, and I'll let you know about it. 
By the moment, I would not recommend you to use the watermark feature, which is the unique feature that doesn't works currently in Docker.

**Comment by sonu27** [comment] 2015-10-06 14:10
Thanks man.

**Off topic**
I'm planning on creating an image service for Firebox.com. We have multiple images for a product, multiple sizes (some with watermarks). e.g. http://media.firebox.com/pic/p7344_column_grid_12.jpg that would be generated from an original image when requested and stored on the filesystem if it didn't exist already.

I might write something from scratch in Go. We need GIF support and config for different sizes.
Let me know if you have suggestions.

**Comment by h2non** [comment] 2015-10-06 14:28
Bad short answer: `gif` support is not planned. But `libvips` can handle use via `libmagick` bindings.

**Comment by h2non** [comment] 2015-10-06 21:47
As I said before, this issue is generated due to `libpango` dependency is missing when compiling `libvips`. This can be easily fixed from Dockerfile, so I moved the request to the original maintainer of the parent image I'm using in the Dockerfile. 

Hopefully that is fixed now, but the Docker image is not available yet, so I'll let you know.

Just to clarify, for now there's not compatibility issue with latest versions of `libvips`.

**Closed by h2non** 2015-10-06 21:47 UTC
Labels: help wanted

**Comment by h2non** [comment] 2015-10-06 22:27
I've just pushed a fresh version, just pull it from Docker hub:
```bash
docker pull h2non/imaginary
```

All the watermark feature should work now. Cheers!

**Comment by sonu27** [comment] 2015-10-07 09:10
Brilliant, all works.

Thanks
